name: Nathan Ankomah-Mensah Website
# markdown: kramdown
markdown: redcarpet
redcarpet:
  extensions: ["strikethrough"]
permalink: /blog/:year/:month/:day/:title
baseurl: ""
url: "https://Natemen96.github.io"
theme: jekyll-theme-dinky