name: Nathan Ankomah-Mensah Website
# markdown: kramdown
markdown: redcarpet
redcarpet:
  extensions: ["strikethrough"]
katex: true
permalink: /blog/:year/:month/:day/:title
baseurl: "/"
url: "https://Natemen96.github.io"


# theme: jekyll-theme-dinky
# remote_theme: pages-themes/dinky