name: Nathan Ankomah-Mensah Website
# markdown: kramdown
markdown: redcarpet
redcarpet:
  extensions: ["strikethrough"]
katex: true
permalink: /blog/:year/:month/:day/:title
baseurl: "/about"
baseurl: "/blog"
baseurl: "/cv"
url: "https://Natemen96.github.io"


theme: jekyll-theme-dinky