name: Nathan Ankomah-Mensah Website
# markdown: kramdown
markdown: redcarpet
redcarpet:
  extensions: ["strikethrough"]
permalink: /blog/:year/:month/:day/:title
baseurl: 
url:
theme: jekyll-theme-dinky